plugins {
    id 'java'
    id 'net.neoforged.gradle' version '7.0.79'
}

group = 'com.smartmobs'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
    maven {
        name = "NeoForged"
        url = "https://maven.neoforged.net/releases"
    }
}

dependencies {
    implementation 'net.neoforged:neoforge:21.1.59'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}