modLoader="neoforge"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Lkthuman/SmartMobs/issues"

[[mods]]
modId="smartmobs"
displayName="SmartMobs"
credits="Developed by Lkthuman"
authors="Lkthuman"
displayURL="https://github.com/Lkthuman/SmartMobs"
description="A Minecraft mod that makes mobs smarter and more challenging"
version="1.0.0"